
import {faCircleUser} from "@fortawesome/free-solid-svg-icons"
export const usersData = [

    {   id:1,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
},
    {   id:2,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
    },
    {   id:3,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
    },
    {   id:4,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
    },
    {   id:5,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
    },
    {   id:6,
        image:faCircleUser,
        name : "racem",
        createdAt : Date.now(),
        email : "racem@gmail.com",
        phoneNumber : "11111111",
    },
]